version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - 'apt install zip unzip'
    pre_build:
        commands:
            - 'rm -rf node_modules'
            - 'npm install'
    build:
        commands:
            - 'echo Build started on `date`'
            - 'npm run build'
artifacts:
    files:
        - preInstall.bat
        - preinstall.ps1
        - appspec.yml
        - 'dist/**/*'
    name: adminportal
