export const getMissingPartQuery = `
query($params: ListRequestType!)
{
  receipts(receiptListRequest:$params)
  {
    idReceiving
    tagNumber
    carrierName
    clientCode
    clientName
    idClient
    packingSlipNumber
    trackingNumber
    receivedOn
    papersCount
    picturesCount
    m2MPONumber
    m2MReceiverNumber
    m2MReceivedDt
    addedInM2MBy
    parts{
      idReceivingDetail
      idReceiving
      binNumber
      lotNumber
      packageQtyReceived
      pallet
      revisionNumber
      partNumber
      qtyReceived
      box
      mappedPartNumber
      mappedRevisionNumber
      scanSerialNumber
      scanLeft
      qtyUOM
      createdBy
      createdDt
    }
    discrepancies(isDeleted:false){
      id
      name
    }
    attachments(isDeleted:false){
      supportingDocuments{
        fileName
        url
        id
      }
      pictures{
        fileName
        url
        id
      }
    }
  }
}`;
